=== borkdominik/CM2KG/at.ac.tuwien.big.msm.cmgba.graphml/AdoxxInstances/ArchiV2/adoxml31.dtd
<!--
*******************************************************************************
ADONIS for Windows

(C) COPYRIGHT BOC - Business Objectives Consulting 1995 - 2010
All Rights Reserved
Use, duplication or disclosure restricted by BOC
Vienna, 1995 - 2010
*******************************************************************************

This *D*ocument *T*ype *D*escription (DTD) contains
the current SGML specification for ADONIS XML import/export.
-->

<!ELEMENT ADOXML (ATTRIBUTEPROFILES?, MODELS?, APPLICATIONMODELS?, MODELGROUPS?)>
<!ATTLIST ADOXML
  version    CDATA #REQUIRED
  date       CDATA #REQUIRED
  time       CDATA #REQUIRED
  database   CDATA #IMPLIED
  username   CDATA #IMPLIED
  adoversion CDATA #REQUIRED
>
<!ELEMENT ATTRIBUTEPROFILES (ATTRPROFDIR+ | ATTRIBUTEPROFILE+)>
<!ELEMENT ATTRIBUTEPROFILE ((ATTRIBUTE | RECORD | INTERREF)*)>
<!ATTLIST ATTRIBUTEPROFILE
  class   CDATA #REQUIRED
  name    CDATA #REQUIRED
  version CDATA #REQUIRED
  applib  CDATA #REQUIRED
>
<!ELEMENT ATTRPROFDIR (ATTRIBUTEPROFILE*, ATTRPROFDIR*)>
<!ATTLIST ATTRPROFDIR
  name CDATA #REQUIRED
>
<!ELEMENT MODELS (MODEL+)>
<!ELEMENT MODEL (MODELATTRIBUTES, INSTANCE*, CONNECTOR*)>
<!ATTLIST MODEL
  id        ID    #IMPLIED
  name      CDATA #REQUIRED
  version   CDATA #REQUIRED
  modeltype CDATA #REQUIRED
  libtype   CDATA #REQUIRED
  applib    CDATA #REQUIRED
>
<!ELEMENT MODELATTRIBUTES ((ATTRIBUTE | RECORD)*)>
<!ELEMENT INSTANCE ((ATTRIBUTE | RECORD | INTERREF)*)>
<!ATTLIST INSTANCE
  id    ID    #IMPLIED
  class CDATA #REQUIRED
  name  CDATA #REQUIRED
>
<!ELEMENT CONNECTOR (FROM, TO, (ATTRIBUTE | RECORD | INTERREF)*)>
<!ATTLIST CONNECTOR
  id    ID    #IMPLIED
  class CDATA #REQUIRED
>
<!ELEMENT FROM EMPTY>
<!ATTLIST FROM
  class    CDATA #REQUIRED
  instance CDATA #REQUIRED
>
<!ELEMENT TO EMPTY>
<!ATTLIST TO
  class    CDATA #REQUIRED
  instance CDATA #REQUIRED
>
<!ELEMENT ATTRIBUTE (#PCDATA)>
<!ATTLIST ATTRIBUTE
  name CDATA #REQUIRED
  type CDATA #REQUIRED
>
<!ELEMENT RECORD (ROW*)>
<!ATTLIST RECORD
  name CDATA #REQUIRED
>
<!ELEMENT ROW ((ATTRIBUTE | INTERREF)*)>
<!ATTLIST ROW
  id     ID    #IMPLIED
  number CDATA #IMPLIED
>
<!ELEMENT INTERREF (IREF*)>
<!ATTLIST INTERREF
  name CDATA #REQUIRED
>
<!ELEMENT IREF EMPTY>
<!ATTLIST IREF
  type       CDATA #REQUIRED
  tmodeltype CDATA #REQUIRED
  tmodelname CDATA #REQUIRED
  tmodelver  CDATA #REQUIRED
  tclassname CDATA #IMPLIED
  tobjname   CDATA #IMPLIED
>
<!ELEMENT APPLICATIONMODELS (APPLICATIONMODEL+)>
<!ELEMENT APPLICATIONMODEL (MODELREFERENCE+)>
<!ATTLIST APPLICATIONMODEL
  name   CDATA #REQUIRED
  applib CDATA #REQUIRED
>
<!ELEMENT MODELREFERENCE EMPTY>
<!ATTLIST MODELREFERENCE
  name      CDATA #REQUIRED
  version   CDATA #REQUIRED
  modeltype CDATA #REQUIRED
  libtype   CDATA #REQUIRED
>
<!ELEMENT MODELGROUPS (MODELGROUP+)>
<!ELEMENT MODELGROUP (MODELREFERENCE*, MODELGROUP*)>
<!ATTLIST MODELGROUP
  name CDATA #REQUIRED
>

=== borkdominik/CM2KG/TestInstances/ADOxx/adoxx5_team_smajevic.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ADOXML SYSTEM "adoxml31.dtd">
<ADOXML version="3.1" date="17.01.2021" time="22:07" database="adoxxdb" username="muhamed2" adoversion="Version 5.1">
<MODELS>
<MODEL id="mod.19809" name="test" version="" modeltype="Business Layer" libtype="bp" applib="TEAM v0.5-Smajevic">
<MODELATTRIBUTES>
<ATTRIBUTE name="Version number" type="STRING"></ATTRIBUTE>
<ATTRIBUTE name="Author" type="STRING">muhamed2</ATTRIBUTE>
<ATTRIBUTE name="Creation date" type="STRING">17.01.2021, 21:42</ATTRIBUTE>
<ATTRIBUTE name="Date last changed" type="STRING">17.01.2021, 22:06:54</ATTRIBUTE>
<ATTRIBUTE name="Last user" type="STRING">muhamed2</ATTRIBUTE>
<ATTRIBUTE name="Keywords" type="STRING"></ATTRIBUTE>
<ATTRIBUTE name="Comment" type="STRING"></ATTRIBUTE>
<ATTRIBUTE name="Model type" type="ENUMERATION">Current model</ATTRIBUTE>
<ATTRIBUTE name="State" type="ENUMERATION">In process</ATTRIBUTE>
<ATTRIBUTE name="Reviewed on" type="STRING"></ATTRIBUTE>
<ATTRIBUTE name="Reviewed by" type="STRING"></ATTRIBUTE>
<ATTRIBUTE name="Description" type="STRING"></ATTRIBUTE>
<ATTRIBUTE name="Number of objects and relations" type="INTEGER">9</ATTRIBUTE>
<ATTRIBUTE name="World area" type="STRING">w:20.05cm h:28.75cm minw:5cm minh:5cm</ATTRIBUTE>
<ATTRIBUTE name="Grid" type="STRING"></ATTRIBUTE>
<ATTRIBUTE name="Zoom" type="INTEGER">100</ATTRIBUTE>
<ATTRIBUTE name="Viewable area" type="STRING">VIEW representation:graphic
GRAPHIC x:-16 y:-16 w:1537 h:933 scale:1
TABLE
</ATTRIBUTE>
<ATTRIBUTE name="Current mode" type="STRING"></ATTRIBUTE>
<ATTRIBUTE name="Base name" type="STRING">test</ATTRIBUTE>
<ATTRIBUTE name="Access state" type="ENUMERATION">write</ATTRIBUTE>
<ATTRIBUTE name="Current page layout" type="STRING"></ATTRIBUTE>
<ATTRIBUTE name="Connector marks" type="STRING"></ATTRIBUTE>
<ATTRIBUTE name="Type" type="STRING">Business Layer</ATTRIBUTE>
<ATTRIBUTE name="Change counter" type="INTEGER">72</ATTRIBUTE>
<ATTRIBUTE name="Font size" type="INTEGER">0</ATTRIBUTE>
<ATTRIBUTE name="Context of version" type="STRING"></ATTRIBUTE>
<ATTRIBUTE name="Position" type="STRING"></ATTRIBUTE>
<ATTRIBUTE name="External tool coupling" type="STRING"></ATTRIBUTE>
<ATTRIBUTE name="__GfxThumb__" type="LONGSTRING">iVBORw0KGgoAAAANSUhEUgAAALIAAAEACAIAAACYnbv1AAAACXBIWXMAAAsTAAALEwEAmpwYAAAJIElEQVR4nO3dIXPb2BqH8b+n91vYMwXROUATnIDSgmpEPAEtXHYDfReE7BR2LjHYmN2FhQnomCguWFrQ4I6AjhbsjP0xdnyBk9RJ3rRuKsmy8vzIpmlWPk2fyq9kS+ktl0sBt/1r2wtAG5EFDGQBw2OyKMsyilSWkqIoqnpF33/oZh/yaVquCaenF1cfhfX/fv38crkMF6cXy3B6ehFCuDj992m4tYXV119crP67tLa2/sG9jd/amvGZW1+Nuhh7i3JyHNITTSaF5FOfTVy6/rtZ4UeJirwIvijyOB3NJhM3GoW1r/f5dDp9Fw/fazrxca7bW/PKlPps4kaj6P7jFscTxUpHaTYJqaZXK8nP8+H7kySKolTZTElS8z+Wp+5+FmWWf8mVxbn8UNPxVMOTtPj620FykhT7JEkSHR/PfHz1W2mq8Xiq4YnPJe37JNL0/F2u/dtbGzkdj6cantx9ZK9plulLPhzG2SyTT7Pp1UryL/vDP66fPPKiVMITSa3uZJEX5SiN9+V9nhcq8ngY50VY/6twV2Xk746Pp5LiE6fpeDZRrlg3X39j/3WsO1ub3Wz26i93talYXxS/VS4pSfVi7D+NXHG1knh/bZOxp4na/fDTTgPP7uHiwccIp6f3xg9UrrfkLCfu4bwFDGQBw90sSomBDutZlLOZEpe9GOvtSaogpxBc4sIsOFdkIfW6+aWTpBBCIaVFEUapSikEl3Dk2AnrWUTSrAzaj71CkBQkqbw6UeFXx6Wl5BRCUFHIe3kpeO8UKcyC+QDYRQ8diZSzMuJf/pPFASoMHInAQBYwkMV29Hq9Crd2dnb2+vXrCjdIFluz/OfPSrbTe/ayku2sI4td1Xv2sqqw7iOLrfprob3+thdhIIstWsyyhfzCub4khYWcxuNPw+GvTpfBHbhwGQq59CDaU/lx9ZkPv0wH74dy6W+qc4dBFlvlJc2zMJcOU82DBtJz6fL6hPG8kKSDSIug+ertTa9jSX1Jp7//9z+//lbTujidtR29Xq/CkZMjETSBLNql/PghuEOnz1km7w+dzsfFi6HvJ68anUzJol0iNwhSCMpzea/IPY+L7/9flWO22A5mC+wesoCl7isOVo9ydnbW+Y9vfrn5t6Uqmz/uhmrfWyyXy/Pz86fw8Zs3bx73bWmh2kfOXq9X+UDUWufn5934kzJbVKkbTaiBLFq+t6xQl/aLTewtuvGdelJqz6Kmf0MtvPqtS/vFXZwtVle/hUkm7yXnnEKWFT5NFYJUFFPvhy5JonJ2nGnoJamQUqcsK+TTUX3Xv3Rmv7iLs8Xq6rdprmEqF0IImp6fx2/91bsUchWSc2UZuTjP5L2c0uAUyftK13FHl2aLbrwmUpbl15v+lbOZXNL8/fjI4kceoEPfrO/ivAUM3WhCuzlbtFSX9ouct4BhV89btFCn9ovVviB737b/fI3aidf0N9HEk8jZ2VkDj9Iey3a/pr8JDlA7ouJj4wr3PA95aP9W2Z9BUg3vUPqGHV325rZ8JHL33c+PvVS3jov5v62SlVe17Mp3ya06EvmBS3W19j2t73r+jT1y5a3VsrOcm16q2z5bXfmy6mPjJl4qe2gaavklNN96uIpW3vCyN8dZzi7o5mxxfU+Py+D6CotiOvcnh0X22adHLnwYTwfDoeT07pf5+7eD4PoKn6Wj5FXda/++3V35t7VhtlgEyWkh9RUW0jzX3woDr4HCpTSQ5pKKoP19XX/NoCguk1cHrHyF2cLGbFGtNs4WN/d4GI//Hg5fO/d5PNbw5CjZq2mBlbm38kWWzb0/rPvuFN2cLe64ucdDrBdyCkHxcKDQ0pvSrbu/cvmBa/aOJZVow2xxz95BImnvejTbO9qZH3t6d+X9ZlZe+WzBu7M6Yvdue/KNFbf/NPBDWrXyTs0Wu7sj2d2Vb2jLs0ULj8021KqVd+q8BVqrG1eVPXWdmi3QWq08b4EfxGyBJjBbdAGzBZrAbNEFzBZoArNFFzBboAnMFl3AbIEmMFt0AbMFmrDN2aLX61W4taccX9fey7m7NzJom069l/O23b2RwZZ1fbbY3RsZdEurzlusfjbwwfW1FUeRlPxv7XLNvaPR2kW97CRudG22QFU6OFt09XYAjenkbNGW2wHgRhtmi/7VBd17itSXDq52A9c7gz9eHUhKrj8TqS+JXcW6JzFb3L+RQZapgdsB7LQOzhZ3mLcDqGlt3dDJ2eKe3b2RQVe0YbbAz+rabMFrGVWpdrbY8vstqm38yb6C2rXZ4sn+RbYcs0UX8F5ONIH3cnZB12YLtBOzRRcwW6ARdf8wtOU2fi7o0/y4Qk08iSwb/7mgT/PjCnEkAgMjJwxkAQNZwEAWMJAFDGQBA1nAQBYwkAUMZAEDWcBQWRZV3QiL9+y0QTVZPPpnjt+5TmT5z5+rz1DGdtX2JLLxzdFueuJSovaoKYtNb45Wz6PjZ9W2t9js5mg3zxpolWrehvPo2cLY1LOXTJ1bxwEqDBVnUX68lDtQuAxOxXjuTw4V5LTICvn0INlT+fH3TC+85JxC6Dt9zjTw7iDZq3Yh+CmV7y3mQasDkL70SXuHCouguTSQVP61iNzzPJP3CkGSIidlkh55T2fUhNkCBmYLGMgChmqyWC6XFb4mUsl28DOqvHyoqsubGCy2jqvKYGC2gIEsYCALGMgCBrKAgSxgIAsYyAIGsoCBLGAgCxjIAgaygIEsYCALGMgCBrKAgSxgIAsYyAIGsoCBLGAgCxjIAgaygIEsYCALGMgCBrKAgSxgIAsYyAIGsoCBLGAgCxjIAgaygIEsYCALGMgCBrKAgSxgIAsYyAIGsoCBLGAgCxjIAgaygIEsYCALGMgCBrKAgSxgIAsYyAIGsoCBLGAgCxjIAgaygIEsYCALGMgCBrKAgSxgIAsYyAIGsoCBLGAgCxjIAgaygIEsYCALGMgCBrKAgSxgIAsYyAIGsoCBLGAgCxjIAgaygIEsYCALGMgCBrKAgSxgIAsYyAIGsoCBLGAgCxjIAgaygIEsYCALGMgCBrKAgSxgIAsYyAIGsoCBLGAgCxjIAgaygIEsYCALGMgCBrKAgSxgIAsYyAIGsoCBLGAgCxjIAgaygIEsYCALGP4PPGqioyzh6XMAAAAASUVORK5CYII=</ATTRIBUTE>
<ATTRIBUTE name="Method GraphRep" type="STRING">GRAPHREP

FONT &quot;Arial&quot; h:20pt color:black
TEXT (&quot;ArchiMate&quot;) y:-3cm w:c h:c
FONT &quot;Arial&quot; h:11pt color:black
TEXT (&quot;Enterprise Architecture Modeling&quot;) y:-2.4cm w:c h:c

PEN color:white style:null
RECTANGLE x:-3.2cm y:-2cm w:6.85cm h:8.25cm
PEN color:black

FILL color:(rgbval(225, 225, 225))
RECTANGLE x:-3cm y:-2cm w:5cm h:8cm
FONT &quot;Arial&quot; h:10pt color:black
TEXT (&quot;Analysis Model&quot;) x:-2.7cm y:-1.8cm

FILL color:(rgbval(205,203,255))
RECTANGLE x:2.2cm y:-2cm w:1.2cm h:8cm
FONT &quot;Arial&quot; h:10pt color:black
TEXT (&quot;M&quot;) x:2.7cm y:-0.5cm
TEXT (&quot;o&quot;) x:2.75cm y:0cm
TEXT (&quot;t&quot;) x:2.8cm y:0.5cm
TEXT (&quot;i&quot;) x:2.8cm y:1cm
TEXT (&quot;v&quot;) x:2.8cm y:1.5cm
TEXT (&quot;a&quot;) x:2.75cm y:2cm
TEXT (&quot;t&quot;) x:2.8cm y:2.5cm
TEXT (&quot;i&quot;) x:2.8cm y:3cm
TEXT (&quot;o&quot;) x:2.75cm y:3.5cm
TEXT (&quot;n&quot;) x:2.75cm y:4cm

FILL color:(rgbval(247,224,171))
RECTANGLE x:-2.7cm y:-1.3cm w:4.4cm h:1cm
FONT &quot;Arial&quot; h:10pt color:black
TEXT (&quot;Strategy&quot;) x:-2.5cm y:-0.8cm

FILL color:(rgbval(255, 253, 188))
RECTANGLE x:-2.7cm y:-0.1cm w:4.4cm h:1cm
FONT &quot;Arial&quot; h:10pt color:black
TEXT (&quot;Business&quot;) x:-2.5cm y:0.4cm

FILL color:(rgbval(186, 250, 253))
RECTANGLE x:-2.7cm y:1.1cm w:4.4cm h:1cm
FONT &quot;Arial&quot; h:10pt color:black
TEXT (&quot;Application&quot;) x:-2.5cm y:1.6cm

FILL color:(rgbval(221,255,223))
RECTANGLE x:-2.7cm y:2.3cm w:4.4cm h:1cm
FONT &quot;Arial&quot; h:10pt color:black
TEXT (&quot;Technology&quot;) x:-2.5cm y:2.8cm

FILL color:(rgbval(172,255,174))
RECTANGLE x:-2.7cm y:3.5cm w:4.4cm h:1cm
FONT &quot;Arial&quot; h:10pt color:black
TEXT (&quot;Physical&quot;) x:-2.5cm y:4.0cm

FILL color:(rgbval(255,222,224))
RECTANGLE x:-2.7cm y:4.7cm w:4.4cm h:1cm
FONT &quot;Arial&quot; h:10pt color:black
TEXT (&quot;Implementation/Migration&quot;) x:-2.5cm y:5.2cm</ATTRIBUTE>
</MODELATTRIBUTES>
<INSTANCE id="obj.19811" class="Grouping" name="Grouping-19811">
<ATTRIBUTE name="Position" type="STRING">NODE x:8.32cm y:8.22cm w:13.5cm h:8cm index:1</ATTRIBUTE>
<ATTRIBUTE name="External tool coupling" type="STRING"></ATTRIBUTE>
<ATTRIBUTE name="Layer label" type="ENUMERATION">No</ATTRIBUTE>
<ATTRIBUTE name="Notes" type="LONGSTRING"></ATTRIBUTE>
<ATTRIBUTE name="Description" type="LONGSTRING"></ATTRIBUTE>
</INSTANCE>
<INSTANCE id="obj.19822" class="Business collaboration" name="Business collaboration-19822">
<ATTRIBUTE name="Position" type="STRING">NODE x:13cm y:6.5cm w:2.8cm h:1.4cm index:2</ATTRIBUTE>
<ATTRIBUTE name="External tool coupling" type="STRING"></ATTRIBUTE>
<ATTRIBUTE name="Layer label" type="ENUMERATION">No</ATTRIBUTE>
<ATTRIBUTE name="Notes" type="LONGSTRING"></ATTRIBUTE>
<ATTRIBUTE name="Description" type="LONGSTRING"></ATTRIBUTE>
<ATTRIBUTE name="Icon" type="ENUMERATION">No</ATTRIBUTE>
</INSTANCE>
<INSTANCE id="obj.19826" class="Business collaboration" name="Business collaboration-19826">
<ATTRIBUTE name="Position" type="STRING">NODE x:6cm y:6.5cm w:2.8cm h:1.4cm index:3</ATTRIBUTE>
<ATTRIBUTE name="External tool coupling" type="STRING"></ATTRIBUTE>
<ATTRIBUTE name="Layer label" type="ENUMERATION">No</ATTRIBUTE>
<ATTRIBUTE name="Notes" type="LONGSTRING"></ATTRIBUTE>
<ATTRIBUTE name="Description" type="LONGSTRING"></ATTRIBUTE>
<ATTRIBUTE name="Icon" type="ENUMERATION">No</ATTRIBUTE>
</INSTANCE>
<INSTANCE id="obj.19829" class="Business collaboration" name="Business collaboration-19829">
<ATTRIBUTE name="Position" type="STRING">NODE x:6cm y:10cm w:2.8cm h:1.4cm index:4</ATTRIBUTE>
<ATTRIBUTE name="External tool coupling" type="STRING"></ATTRIBUTE>
<ATTRIBUTE name="Layer label" type="ENUMERATION">No</ATTRIBUTE>
<ATTRIBUTE name="Notes" type="LONGSTRING"></ATTRIBUTE>
<ATTRIBUTE name="Description" type="LONGSTRING"></ATTRIBUTE>
<ATTRIBUTE name="Icon" type="ENUMERATION">No</ATTRIBUTE>
</INSTANCE>
<INSTANCE id="obj.19910" class="Business actor" name="Business actor-19910">
<ATTRIBUTE name="Position" type="STRING">NODE x:15.5cm y:3cm w:2.8cm h:1.4cm index:5</ATTRIBUTE>
<ATTRIBUTE name="External tool coupling" type="STRING"></ATTRIBUTE>
<ATTRIBUTE name="Layer label" type="ENUMERATION">No</ATTRIBUTE>
<ATTRIBUTE name="Notes" type="LONGSTRING"></ATTRIBUTE>
<ATTRIBUTE name="Description" type="LONGSTRING"></ATTRIBUTE>
<ATTRIBUTE name="Icon" type="ENUMERATION">No</ATTRIBUTE>
<INTERREF name="Responsible for"></INTERREF>
</INSTANCE>
